### ISSUE TITLE
Installation error on mac

### ISSUE THREAD

**Issue by scottcohn97** [anthonynorth/rscodeio#12]
Unable to install on Mac. Error message below: 

<img width="635" alt="Screen Shot 2019-07-08 at 11 07 16 PM" src="https://user-images.githubusercontent.com/7584419/60856436-34f3a700-a1d5-11e9-8d85-b00ad1986802.png">

**Comment by MilesMcBain** [comment]
This is an interesting one. R's been unable to find `pillar`, but this is only a suggested dependency of `fs` (a dependency of `rscodeio`).

Could your R library be in an inconsistent state? Does it persist if you restart your R/RStudio session?

**Comment by scottcohn97** [comment]
Yes -- it does persist. Below are the messages I see when I try to install, including when I try to separately install `Pillar`. When trying to install `Pillar`, I get an error telling me the installation had a `non-zero exit status`.



<img width="577" alt="Screen Shot 2019-07-08 at 11 41 54 PM" src="https://user-images.githubusercontent.com/7584419/60857856-20fe7400-a1da-11e9-9625-a4fd7288fbf4.png">

<img width="598" alt="Screen Shot 2019-07-08 at 11 42 09 PM" src="https://user-images.githubusercontent.com/7584419/60857862-23f96480-a1da-11e9-8db0-7ab3dca58664.png">

<img width="595" alt="Screen Shot 2019-07-08 at 11 42 20 PM" src="https://user-images.githubusercontent.com/7584419/60857865-25c32800-a1da-11e9-828c-6648bbc6ec1a.png">

**Comment by MilesMcBain** [comment]
Yeah it seems like a problem with the dependencies rather than `rscodeio`. Try install CRAN only (2), and (n) to install newer versions that require compilation.

**Comment by scottcohn97** [comment]
The `pillar` issue remains. :(

<img width="449" alt="Screen Shot 2019-07-09 at 10 37 28 AM" src="https://user-images.githubusercontent.com/7584419/60897143-8f245480-a235-11e9-9d83-08a57c8cc347.png">

**Comment by rabdill** [comment]
For what it's worth, I installed on Mac without running into this issue. Using R 3.6.0, RStudio 1.2.1335, and OSX 10.14.3.

**Comment by scottcohn97** [comment]
@rabdill Thank you for this. I updated my version of R and it worked.
