### ISSUE TITLE
Git Review Changes Window Title and Bar colors

### ISSUE THREAD

**Issue by jhollist** [anthonynorth/rscodeio#13]
The text color and the bar color appears to be the same on the Git Review Changes window (eg.  Git tab, then commit button).  This is what I get on my machine:

![image](https://user-images.githubusercontent.com/5438539/60909439-3ca26280-a24c-11e9-9e01-4f677baba8b6.png)

**Comment by anthonynorth** [comment]
Duplicate of #11
This should be fixed; please update and reinstall theme.

**Comment by jhollist** [comment]
Sorry!  Didn't check the closed issues.  It is fixed now.  Thanks.
