### ISSUE TITLE
Feedback: Switching themes works out of the box

### ISSUE THREAD

**Issue by jmbuhr** [anthonynorth/rscodeio#18]
Just wanted to let you know that switching themes works for me out of the box, even with changing menu-elements. That's really cool so, I will investigate, why I don't need the `rscodeio::deactivate_menu_theme` functions.

I am switching between themes via `rstudioapi::applyTheme("rscodeio")`, which I packaged up as an addin: [link to repo](https://github.com/jannikbuhr/themeSwitch).

Thank you for this amazing theme!

**Comment by anthonynorth** [comment]
Once installed, the menu theme is applied when any dark editor theme is applied; `rscodeio::deactivate_menu_theme` will revert the menu theme back to the default dark menu theme for dark editor themes.
https://github.com/rstudio/rstudio/blob/master/src/cpp/desktop/DesktopUtils.cpp#L131

**Comment by jannikbuhr** [comment]
Right, now I get it! Thanks :)

**Comment by salim-b** [comment]
@anthonynorth I think this issue can be safely closed.
