### ISSUE TITLE
Issues with fonts

### ISSUE THREAD

**Issue by aswansyahputra** [anthonynorth/rscodeio#28]
Hi!

I love to combine this theme with [Fira Code iScript](https://github.com/kencrocken/FiraCodeiScript) font. The combination looks great in my Ubuntu 18.04 LTS !
However, if close and re-open the RStudio the editor font choice is restarted to default font. Screenshoots are attached:

**When applying rscodeio + Fira Code iScript:**
![Screenshot from 2019-08-14 05-31-36](https://user-images.githubusercontent.com/12567035/62982161-8be44000-be55-11e9-8280-04e10483a455.png)

**After closing and re-opening RStudio:**
![Screenshot from 2019-08-14 05-32-37](https://user-images.githubusercontent.com/12567035/62982168-91da2100-be55-11e9-91cf-bf9e154070f5.png)

Thanks for this amazing theme!

**Comment by anthonynorth** [comment]
The font configuration being reset is unlikely to be related to rscodeio. The package only changes the active theme (not related to editor font) and replaces the qt stylesheet for the top menu.

Can you try replicate this with another theme?

**Comment by aswansyahputra** [comment]
Yes, I have figured out that it indeed was caused by a problem with my RStudio. I fixed it by wiped out configuration files and re-installed RStudio.

I really love this themes, looking forward to light themes variant as in #29. Thanks for the great work!
