### ISSUE TITLE
Bold font text editing in R Markdown

### ISSUE THREAD

**Issue by tallguyjenks** [anthonynorth/rscodeio#30]
hello, this is a minor bug, but when writing RMarkdown documents with this theme and I user the:
'\*\*bold text\*\*' markdown it works as intended but the cursor for editing appears to be push in, I don't know how to describe this well but the font seems to grow a little in size and If I click someone in the text and start typing its places my input in an unintended location usually a few characters to either direction.

**Comment by juliancabezas** [comment]
Hi, I am having the same problem, the cursor shifts when I use this theme in rmarkdown and apply **bold**, how did you solved it?
