### ISSUE TITLE
Fira code 

### ISSUE THREAD

**Issue by mkarmstrong** [anthonynorth/rscodeio#32]
I use font Fira code [https://github.com/tonsky/FiraCode](url) in rstudio but it is not implement correctly when using rscodeio theme. The font is applied correctly to text but not to special characters. Any intuition as to why this might be? 
Fantastic theme!
Many thanks,
Matt

**Comment by mkarmstrong** [comment]
Got it, if anyone was interested, find the code shown below in the theme file and change off to on:

.rstudio-themes-flat .ace_editor_theme {
  background-color: var(--editor-background);
  color: var(--editor-foreground);
  font-feature-settings: "liga" off, "calt" off;
  line-height: 1.3 !important;
}

**Comment by anthonynorth** [comment]
This was a bug I fixed a while ago (c3ad6dd). Re-install the package and the theme to apply the fix.

**Comment by salim-b** [comment]
@anthonynorth I think this issue can be safely closed.
