### ISSUE TITLE
Nothing has been changed

### ISSUE THREAD

**Issue by seed-of-apricot** [anthonynorth/rscodeio#38]
The layout is not changed after the installation & restart.

Install

![image](https://user-images.githubusercontent.com/26666870/78292180-7e122680-74db-11ea-9623-5c5acfd24fb1.png)

Restart

![image](https://user-images.githubusercontent.com/26666870/78292256-9a15c800-74db-11ea-9677-90a71507b65a.png)

Environment:
Windows 10 x64 1903
RStudio 1.2.5033

**Comment by luciorq** [comment]
Hello,

Sorry if I got it wrong, but can you elaborate on what was supposed to happen?

**Comment by seed-of-apricot** [comment]
Sorry for messing up, I was completely misunderstood.  
I thought this tool will also adjust the pane layout automatically (and that was the main function).
