### ISSUE TITLE
Incorrect line numbers

### ISSUE THREAD

**Issue by CGMossa** [anthonynorth/rscodeio#7]
Currently, the line numbering becomes messed up, upon installation of this theme.
Every other line is skipped, but the total no. of lines is still the same. 

![image](https://user-images.githubusercontent.com/1063624/60811785-449ccc80-a190-11e9-896b-57826b35b258.png)

I hope someone can indicate what is going on here, as I think it is a really nice theme, that I wholeheartedly want to use and support.

**Comment by rmflight** [comment]
Can confirm line numbers are messed up on Ubuntu 18.04 LTS, RStudio 1.3.90, R 3.5.1

See the same pattern as @CGMossa

**Comment by MikeJohnPage** [comment]
Line numbers work as **expected** for Ubuntu 18.04 LTS, R 3.6.0, RStudio 1.2.1335:

```r
> session_info()
─ Session info ─────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.0 (2019-04-26)
 os       Ubuntu 18.04.2 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language en_AU:en                    
 collate  en_AU.UTF-8                 
 ctype    en_AU.UTF-8                 
 tz       Europe/London               
 date     2019-07-08
```

**Comment by rmflight** [comment]
Hmmm. So something up with RStudio 1.3.x probably then. I will have to try regressing and see what happens then.

**Comment by MikeJohnPage** [comment]
Let me know how it goes, as I was thinking of upgrading RStudio, but will hold off if this theme is not compatible.

**Comment by CGMossa** [comment]
I too was using RStudio 1.3.

**Comment by MikeJohnPage** [comment]
Apologies if I am missing something, but how are you both using a version > 1.2.1555 (the latest [preview version](https://www.rstudio.com/products/rstudio/download/preview/))?

**Comment by CGMossa** [comment]
We are using a daily build. See [RStudio dailies](https://dailies.rstudio.com/rstudio/oss/windows/).

**Comment by MikeJohnPage** [comment]
Thanks, that is good to know.

**Comment by rmflight** [comment]
Yep. Dailies are pretty awesome, especially if you keep an eye on RStudio's issues feed, then you see when new features get introduced, when subtle bugs get squashed! But then you run into things like this, where things don't quite work correctly.
